import type { MetadataRoute } from "next";

// PWA manifest. Next.js serves this at /manifest.webmanifest automatically
// and wires the <link> tag into the document head when this file exists.
//
// Once installed to home screen on iOS / Android, Agently launches in
// standalone mode (no browser chrome) and uses these colors for the
// splash screen + status bar.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Agently",
    short_name: "Agently",
    description: "India-first creator talent agency operating system. Manage offers, contracts, payments, and campaigns end-to-end.",
    start_url: "/dashboard",
    display: "standalone",
    orientation: "portrait",
    background_color: "#f8fafc",
    theme_color: "#147b6d",
    categories: ["business", "productivity"],
    icons: [
      // Next.js serves the icon files generated by app/icon.tsx and
      // app/apple-icon.tsx automatically. Listing them here lets the OS
      // pick the right size for its launcher / splash screen.
      { src: "/icon", sizes: "32x32", type: "image/png" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png", purpose: "any" },
      // Larger sizes for higher-DPI Android launchers. Marked maskable so
      // launchers can crop into the safe zone without weird letterboxing.
      { src: "/apple-icon", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/apple-icon", sizes: "512x512", type: "image/png", purpose: "maskable" }
    ]
  };
}
